"""Package configuration model and loaders (TOML / JSON)."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any, Dict, List, Optional


NAME_RE = re.compile(r"^[a-zA-Z][a-zA-Z0-9_-]*$")
VERSION_RE = re.compile(
    r"^\d+(\.\d+)*([a-zA-Z0-9.\-]*)?$"
)


@dataclass
class ModuleSpec:
    """Custom module content under the package."""

    name: str
    content: str = '"""Module generated by py-package-builder."""\n'


@dataclass
class EntryPoint:
    """Console script / entry point definition."""

    name: str
    module: str
    attr: str = "main"

    def as_script(self) -> str:
        return f"{self.name} = {self.module}:{self.attr}"


@dataclass
class PackageConfig:
    """Full package metadata used by init / build / verify."""

    name: str = "my_package"
    version: str = "0.1.0"
    author: str = "Unknown"
    author_email: str = ""
    description: str = "A Python package generated by py-package-builder"
    license: str = "MIT"
    python_requires: str = ">=3.8"
    dependencies: List[str] = field(default_factory=list)
    optional_dependencies: Dict[str, List[str]] = field(default_factory=dict)
    modules: List[ModuleSpec] = field(default_factory=list)
    entry_points: List[EntryPoint] = field(default_factory=list)
    package_dir: str = "."
    keywords: List[str] = field(default_factory=list)
    classifiers: List[str] = field(default_factory=list)
    urls: Dict[str, str] = field(default_factory=dict)
    use_pyproject: bool = True
    use_setup_py: bool = True
    include_readme: bool = True
    include_license: bool = True

    def validate(self) -> List[str]:
        """Return a list of validation error messages (empty if OK)."""
        errors: List[str] = []
        if not self.name or not NAME_RE.match(self.name):
            errors.append(
                f"Invalid package name '{self.name}'. "
                "Use letters, digits, underscore, hyphen; start with a letter."
            )
        if not self.version or not VERSION_RE.match(self.version):
            errors.append(f"Invalid version '{self.version}'.")
        if not self.author:
            errors.append("Author must not be empty.")
        for dep in self.dependencies:
            if not isinstance(dep, str) or not dep.strip():
                errors.append(f"Invalid dependency entry: {dep!r}")
        for ep in self.entry_points:
            if not ep.name or not ep.module:
                errors.append(f"Invalid entry point: {ep}")
        for mod in self.modules:
            if not mod.name or not re.match(r"^[a-zA-Z_]\w*$", mod.name):
                errors.append(f"Invalid module name: {mod.name!r}")
        return errors

    def import_name(self) -> str:
        """Normalize package import name (hyphens -> underscores)."""
        return self.name.replace("-", "_")

    def to_dict(self) -> Dict[str, Any]:
        data = asdict(self)
        return data

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "PackageConfig":
        modules_raw = data.pop("modules", []) or []
        eps_raw = data.pop("entry_points", []) or []
        known = {f.name for f in cls.__dataclass_fields__.values()}  # type: ignore[attr-defined]
        filtered = {k: v for k, v in data.items() if k in known}
        cfg = cls(**filtered)
        cfg.modules = [
            ModuleSpec(**m) if isinstance(m, dict) else m for m in modules_raw
        ]
        cfg.entry_points = [
            EntryPoint(**e) if isinstance(e, dict) else e for e in eps_raw
        ]
        return cfg


def _load_toml(path: Path) -> Dict[str, Any]:
    try:
        import tomllib  # Python 3.11+
    except ModuleNotFoundError:
        try:
            import tomli as tomllib  # type: ignore
        except ModuleNotFoundError as exc:
            raise RuntimeError(
                "TOML support requires Python 3.11+ (tomllib) or the 'tomli' package."
            ) from exc
    with path.open("rb") as fh:
        return tomllib.load(fh)


def _dump_toml(data: Dict[str, Any], path: Path) -> None:
    try:
        import tomli_w
    except ModuleNotFoundError:
        # Minimal TOML writer for our flat/nested dict needs
        path.write_text(_simple_toml_dumps(data), encoding="utf-8")
        return
    with path.open("wb") as fh:
        tomli_w.dump(data, fh)


def _simple_toml_dumps(data: Dict[str, Any], prefix: str = "") -> str:
    """Very small TOML serializer sufficient for package.builder.toml."""
    lines: List[str] = []
    scalars: Dict[str, Any] = {}
    tables: Dict[str, Any] = {}
    array_tables: Dict[str, List[Any]] = {}

    for key, value in data.items():
        if isinstance(value, dict):
            tables[key] = value
        elif isinstance(value, list) and value and isinstance(value[0], dict):
            array_tables[key] = value
        else:
            scalars[key] = value

    for key, value in scalars.items():
        lines.append(f"{key} = {_toml_value(value)}")

    for key, value in tables.items():
        full = f"{prefix}.{key}" if prefix else key
        lines.append("")
        lines.append(f"[{full}]")
        lines.append(_simple_toml_dumps(value, full).rstrip())

    for key, items in array_tables.items():
        full = f"{prefix}.{key}" if prefix else key
        for item in items:
            lines.append("")
            lines.append(f"[[{full}]]")
            if isinstance(item, dict):
                for ik, iv in item.items():
                    if isinstance(iv, dict) or (
                        isinstance(iv, list) and iv and isinstance(iv[0], dict)
                    ):
                        continue
                    lines.append(f"{ik} = {_toml_value(iv)}")
            else:
                lines.append(_toml_value(item))

    return "\n".join(lines).rstrip() + "\n"


def _toml_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(_toml_value(v) for v in value) + "]"
    if value is None:
        return '""'
    text = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{text}"'


def load_config(path: str | Path) -> PackageConfig:
    """Load PackageConfig from a TOML or JSON file."""
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Config not found: {path}")

    suffix = path.suffix.lower()
    if suffix == ".toml":
        raw = _load_toml(path)
        # Allow top-level [package] table
        if "package" in raw and isinstance(raw["package"], dict):
            data = dict(raw["package"])
            for key in ("modules", "entry_points", "optional_dependencies", "urls"):
                if key in raw and key not in data:
                    data[key] = raw[key]
        else:
            data = raw
    elif suffix == ".json":
        data = json.loads(path.read_text(encoding="utf-8"))
    else:
        raise ValueError(f"Unsupported config format: {suffix} (use .toml or .json)")

    cfg = PackageConfig.from_dict(data)
    errors = cfg.validate()
    if errors:
        raise ValueError("Invalid package config:\n- " + "\n- ".join(errors))
    return cfg


def save_config(cfg: PackageConfig, path: str | Path) -> Path:
    """Persist PackageConfig to TOML or JSON."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    data = cfg.to_dict()
    suffix = path.suffix.lower()
    if suffix == ".toml":
        # Nest under [package] for readability; keep arrays at top level
        payload = {
            "package": {
                k: v
                for k, v in data.items()
                if k not in ("modules", "entry_points", "optional_dependencies", "urls")
            },
            "modules": data.get("modules") or [],
            "entry_points": data.get("entry_points") or [],
            "optional_dependencies": data.get("optional_dependencies") or {},
            "urls": data.get("urls") or {},
        }
        _dump_toml(payload, path)
    elif suffix == ".json":
        path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    else:
        raise ValueError(f"Unsupported config format: {suffix}")
    return path


def default_config(
    name: str = "my_package",
    version: str = "0.1.0",
    author: str = "Unknown",
) -> PackageConfig:
    """Create a sensible default configuration."""
    import_name = name.replace("-", "_")
    return PackageConfig(
        name=name,
        version=version,
        author=author,
        description=f"{name} - generated by py-package-builder",
        modules=[
            ModuleSpec(
                name="core",
                content=(
                    f'"""Core logic for {name}."""\n\n'
                    f"def hello(name: str = \"world\") -> str:\n"
                    f"    return f\"Hello, {{name}}!\"\n"
                ),
            )
        ],
        entry_points=[
            EntryPoint(name=import_name.replace("_", "-"), module=f"{import_name}.cli", attr="main")
        ],
        classifiers=[
            "Programming Language :: Python :: 3",
            "Operating System :: OS Independent",
        ],
        keywords=["python", "package"],
    )